### ISSUE TITLE
Change the template on the Map page

### ISSUE THREAD

**Issue by emylonas** [emylonas/xml-minimal#1]
(perhaps other pages that don't have a TOC or index. 

Is it possible to select a template that uses the whole page - there is too much empty space on the left.

https://emylonas.github.io/xml-minimal/gardens/

**Comment by ccarvel** [comment]
added front matter variable custom_css: gardens 
added liquid logic to end of assets/head/custom.html to check for custom_css and add stylesheet for given css
added gardens.css to /assets/css and reset .page for width and float
