### ISSUE TITLE
Headings on the edition index are unclear

### ISSUE THREAD

**Issue by emylonas** [emylonas/xml-minimal#2]
https://emylonas.github.io/xml-minimal/edition/

The index on the left of the page reads: 

**EDITION** (all caps, bold and with more white space below)
**Libro Azzurro**
then the pages for the introduction and the plants

is it possible to replace "EDITION" with "Libro Azzurro"? or just eliminate EDITION? 

Ultimately Sabrina would like to have the books lists (Rosso, Giallo, etc.) and you can either click an arrow to list the plants, Or don't have the submenus on this page, and just reveal all the plants on the next level down. This is not for now. Just noting it so it's here. Probably should move to new issue when the first part of this one is complete. But taking this into account may affect how the current issue is handled.

**Comment by ccarvel** [comment]
Heading is now Table of Contents
