### ISSUE TITLE
pictures and some formatting on main editions page

### ISSUE THREAD

**Issue by emylonas** [emylonas/xml-minimal#4]
https://emylonas.github.io/xml-minimal/edition/

See section in this google doc https://docs.google.com/document/d/1L8byr7E-mp_VtGWhFb9jZInmDgrCUjVgZD1fgTe39-c/edit under https://emylonas.github.io/xml-minimal/edition/
Sabrina says:
"slightly larger, very nice; 
we might also add the original portrait, cf. image It_02_0028_04862_D_0010v (Libro verde)
Can we allow people to enlarge the image now there and, once enlarged, browsing to the original one?"

For next week, perhaps make the portrait larger. 
I am not sure about adding the original portrait - would that be a second image ? If it's easy to find, that's fine.

Enlarging - only if it's not complicated.
We should have an attribution (can ask Sabrina) and that could be the link. Not sure where the original is.  Can ask.

2nd change: replace the coat of arms with the DeToni title page that is now used on the .../editions/index page.

**Comment by ccarvel** [comment]
replaced images; changed sizes to 30% rather than using px units (slightly larger and proportional across devices);
