### ISSUE TITLE
Individual plants no longer display scientific name

### ISSUE THREAD

**Issue by emylonas** [emylonas/xml-minimal#5]
Is there anything Elli has to do to make this work? Is the XML transform not getting the correct information?

**Comment by ccarvel** [comment]
unsure how this changed--not understanding what's different about the xslt from Nov/Dec--

**Comment by emylonas** [comment]
I realized this late last night - when we moved to multiple herbarium links (Kew, WFO) we changed the location of the link text. 
There is now a new metadata variable for each plant: `plant-taxon-content: "Clematis Vitalba L."` (for plant 5)
should be able to use that and add it in above the Kew WFO links, below the title.

**Comment by emylonas** [comment]
But it may not be populating. checking now

**Comment by emylonas** [comment]
It's a data problem - @emylonas will fix in the xml file.

**Comment by emylonas** [comment]
fixed with c72e249
